Repository mpandrews/8080, pull requests merged in 2020-11, with the labels that each got.

#123 Implement Taito screen
  hardware/si/src/hw_funcs.c
  hardware/si/src/update_keystates.cpp
  hardware/taito/include/taitoScreen.hpp
  hardware/taito/include/taito_start.h
  hardware/taito/src/dummy.cpp
  hardware/taito/src/taitoScreen.cpp
  hardware/taito/src/taito_start.cpp
  src/main.c
  test/hw_funcs_tests.cpp
Labels: hardware lib, space_invaders, taito

#128 Post video cleanup refactor.
  CMakeLists.txt
  hardware/si/include/rom_struct.h
  hardware/si/include/si_proms.c
  hardware/si/src/hw_funcs.c
  hardware/si/src/update_keystates.cpp
  hardware/taito/include/taito_struct.h
  hardware/taito/src/interrupt_hook.c
  hardware/taito/src/taitoScreen.cpp
  hardware/taito/src/taito_start.cpp
  hardware/taito/src/taito_struct_ops.c
  include/cpu.h
  include/hw_func_pointers.h
  roms/balloon
  roms/lunar_rescue
  roms/ozma
  src/cpu_thread.c
  src/cycle_timer.c
  src/hw_func_pointers.c
  src/main.c
  src/other_opcodes.c
  test/hw_funcs_tests.cpp
Labels: enhancement

#129 Implemented sound effects for Sapce Invaders
  .github/workflows/cmake.yml
  .github/workflows/style-enforcement.yml
  README.md
  hardware/si/include/play_sound.h
  hardware/si/include/rom_struct.h
  hardware/si/include/sound.h
  hardware/si/src/hw_funcs.c
  hardware/si/src/play_sound.cpp
  hardware/si/src/sound.c
  hardware/si/src/update_keystates.cpp
  hardware/taito/CMakeLists.txt
  hardware/taito/include/hw_lib_imports.h
  hardware/taito/include/taitoScreen.hpp
  hardware/taito/src/taitoScreen.cpp
  hardware/taito/src/taito_start.cpp
  test/hw_funcs_tests.cpp
Labels: hardware lib, space_invaders

#127 Add color to Taito screen
  hardware/si/include/si_proms.c
  hardware/si/src/hw_funcs.c
  hardware/si/src/proms.c
  hardware/si/src/sound.c
  hardware/taito/include/proms.h
  hardware/taito/include/taitoScreen.hpp
  hardware/taito/include/taito_struct.h
  hardware/taito/src/taitoScreen.cpp
  hardware/taito/src/taito_start.cpp
  hardware/taito/src/taito_struct_ops.c
Labels: hardware lib, space_invaders, taito

#131 Rom mask
  include/cpu.h
  include/opcode_helpers.h
  roms/balloon.mask
  roms/invaders_cv.mask
  roms/lunar_rescue.mask
  roms/ozma.mask
  src/arithmetic_opcodes.c
  src/branch_opcodes.c
  src/cpu_thread.c
  src/data_transfer_opcodes.c
  src/main.c
  src/other_opcodes.c
  test/arithmetic_opcode_tests.cpp
  test/branch_opcode_tests.cpp
  test/data_opcode_tests.cpp
  test/other_opcode_tests.cpp
Labels: 8080 opcodes, bug, taito

#130 Update readme, edit comments
  README.md
  hardware/si/include/rom_struct.h
  space_invaders.gif
  test/hw_funcs_tests.cpp
Labels: enhancement

#132 Added Cmake options for unthrottling and benchmarking.
  CMakeLists.txt
  README.md
Labels: enhancement

#136 Flip coin logic
  hardware/si/src/hw_funcs.c
  hardware/si/src/update_keystates.cpp
Labels: bug

#135 Added READMEs for ROM and hardware stuff.
  README.md
  hardware/README.md
  roms/README.md
Labels: documentation

#134 Added custom laser and UFO sounds.
  .github/workflows/style-enforcement.yml
  hardware/si/include/sound.h
  hardware/si/src/mike_laser.c
  hardware/si/src/mike_ufo.c
  hardware/si/src/play_sound.cpp
  hardware/si/src/sound.c
  hardware/taito/src/taitoScreen.cpp
Labels: enhancement, space_invaders

#137 Print reg bug
  src/cpu_thread.c
Labels: bug

#138 Altair 8K BASIC
  README.md
  hardware/basic/CMakeLists.txt
  hardware/basic/src/hw_funcs.c
  roms/basic
  src/main.c
Labels: hardware lib

#139 Changed the build RPATH to $ORIGIN
  CMakeLists.txt
Labels: bug

#141 Update readme
  README.md
  balloon.png
  lunar.png
  ozma.png
  si.png
Labels: documentation
